In [1]:
print('hello')

hello


In [2]:
print(2+3)

5


In [7]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np
a=np.array([1,2,3,4])
print(a.shape)   #Shape of the Array 'a'
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)  # Shape of the Array 'b'
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(c.shape)  #Shape of the Array 'c'
new_c = c.reshape(4,3) #reshaping into 4 arrays which has 3 elements in it
print(new_c)
new2_c = c.reshape(2,3,2) # For a 3-D array
print(new2_c)
f_arr=b.reshape(-1)  # For flattening a multi-dimensional array
print(f_arr)

(4,)
(2, 3)
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6]


In [30]:
import numpy as np
a = np.array([3,4,5,6,7,8,9])
a[0]    # Accessing the elements in the list..
a[0] + a[2]
for i in a:
    print(i) #Iterating through the 1-D Array
print(a[1:4]) #last index(3) won't be considered for slicing
print(a[2:])
print(a[:5])
print(a[1:5:2]) #prints from 1st index to 5th index but takes 2 gaps.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,4]) # accessing 5th element from 2nd row..
print(b[0,3]) # accessing 4th element from 1st row..
for j in b:
    print(j) #Iterating through the 2-D Array
for j in b:
    for k in j:  #Iterating and getting the elements in the 2-D Array
        print(k)
print(b[1,1:4]) #prints the elements from 1st to 4th index in the 2nd column.
print(b[0,0:3])
d = np.array([2,4,1,6,4,7,9,1])
x = np.where(d == 1)
print(x) # shows where is 1 present in the whole array
ans = np.where(d%2==0) # which index has even numbers and will return the indexes
print(ans)
print(np.sort(d)) # sorts the elements in the array.
g = np.array(['fille','femme','garcon'])
print(np.sort(g))

3
4
5
6
7
8
9
[4 5 6]
[5 6 7 8 9]
[3 4 5 6 7]
[4 6]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
4
[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
[7 8 9]
[1 2 3]
(array([2, 7], dtype=int64),)
(array([0, 1, 3, 4], dtype=int64),)
[1 1 2 4 4 6 7 9]
['femme' 'fille' 'garcon']


In [33]:
!pip install pandas


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
import pandas as pd
l1 = [3,6,8,10,30,22]
s1 = pd.Series(l1)
print(s1)
d1 = {"one":10,"two":20,"three":30}
s2 = pd.Series(d1)
print(s2)
sample_data = {
    "weekdays":['Monday','Tuesday','Friday'],
    "test_score":[10,30,50]
}
df = pd.DataFrame(sample_d)

0     3
1     6
2     8
3    10
4    30
5    22
dtype: int64
one      10
two      20
three    30
dtype: int64
