In [1]:
print('hello')

hello


In [2]:
print(2+3)

5


In [7]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np
a=np.array([1,2,3,4])
print(a.shape)   #Shape of the Array 'a'
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)  # Shape of the Array 'b'
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(c.shape)  #Shape of the Array 'c'
new_c = c.reshape(4,3) #reshaping into 4 arrays which has 3 elements in it
print(new_c)
new2_c = c.reshape(2,3,2) # For a 3-D array
print(new2_c)
f_arr=b.reshape(-1)  # For flattening a multi-dimensional array
print(f_arr)

(4,)
(2, 3)
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6]


In [30]:
import numpy as np
a = np.array([3,4,5,6,7,8,9])
a[0]    # Accessing the elements in the list..
a[0] + a[2]
for i in a:
    print(i) #Iterating through the 1-D Array
print(a[1:4]) #last index(3) won't be considered for slicing
print(a[2:])
print(a[:5])
print(a[1:5:2]) #prints from 1st index to 5th index but takes 2 gaps.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,4]) # accessing 5th element from 2nd row..
print(b[0,3]) # accessing 4th element from 1st row..
for j in b:
    print(j) #Iterating through the 2-D Array
for j in b:
    for k in j:  #Iterating and getting the elements in the 2-D Array
        print(k)
print(b[1,1:4]) #prints the elements from 1st to 4th index in the 2nd column.
print(b[0,0:3])
d = np.array([2,4,1,6,4,7,9,1])
x = np.where(d == 1)
print(x) # shows where is 1 present in the whole array
ans = np.where(d%2==0) # which index has even numbers and will return the indexes
print(ans)
print(np.sort(d)) # sorts the elements in the array.
g = np.array(['fille','femme','garcon'])
print(np.sort(g))

3
4
5
6
7
8
9
[4 5 6]
[5 6 7 8 9]
[3 4 5 6 7]
[4 6]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
4
[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
[7 8 9]
[1 2 3]
(array([2, 7], dtype=int64),)
(array([0, 1, 3, 4], dtype=int64),)
[1 1 2 4 4 6 7 9]
['femme' 'fille' 'garcon']


In [33]:
!pip install pandas


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [41]:
import pandas as pd
l1 = [3,6,8,10,30,22]
s1 = pd.Series(l1)
print(s1)
d1 = {"one":10,"two":20,"three":30}
s2 = pd.Series(d1)
print(s2)
sample_data = {
    "weekdays":['Monday','Tuesday','Friday'],
    "test_score":[10,30,50]
}
df = pd.DataFrame(sample_data)
print(df)
print(df.loc[0])
print(df.loc[1])

0     3
1     6
2     8
3    10
4    30
5    22
dtype: int64
one      10
two      20
three    30
dtype: int64
  weekdays  test_score
0   Monday          10
1  Tuesday          30
2   Friday          50
weekdays      Monday
test_score        10
Name: 0, dtype: object
weekdays      Tuesday
test_score         30
Name: 1, dtype: object


In [44]:
import pandas as pd
df = pd.read_csv('covid_worldwide.csv')

Serial Number           Country  Total Cases  Total Deaths  \
0                1               USA    104196861     1132935.0   
1                2             India     44682784      530740.0   
2                3            France     39524311      164233.0   
3                4           Germany     37779833      165711.0   
4                5            Brazil     36824580      697074.0   
..             ...               ...          ...           ...   
226            227  Diamond Princess          712          13.0   
227            228      Vatican City           29           NaN   
228            229    Western Sahara           10           1.0   
229            230        MS Zaandam            9           2.0   
230            231           Tokelau            5           NaN   

     Total Recovered  Active Cases    Total Test    Population  
0        101322779.0     1741147.0  1.159833e+09  3.348053e+08  
1         44150289.0        1755.0  9.152658e+08  1.406632e+09  
2         39264546.0       95532.0  2.714902e+08  6.558452e+07  
3         37398100.0      216022.0  1.223324e+08  8.388360e+07  
4         35919372.0      208134.0  6.377617e+07  2.153536e+08  
..               ...           ...           ...           ...  
226            699.0           0.0           NaN           NaN  
227             29.0           0.0           NaN  7.990000e+02  
228              9.0           0.0           NaN  6.261610e+05  
229              7.0           0.0           NaN           NaN  
230              NaN           5.0           NaN  1.378000e+03  

[231 rows x 8 columns]

In [45]:
df

Serial Number           Country  Total Cases  Total Deaths  \
0                1               USA    104196861     1132935.0   
1                2             India     44682784      530740.0   
2                3            France     39524311      164233.0   
3                4           Germany     37779833      165711.0   
4                5            Brazil     36824580      697074.0   
..             ...               ...          ...           ...   
226            227  Diamond Princess          712          13.0   
227            228      Vatican City           29           NaN   
228            229    Western Sahara           10           1.0   
229            230        MS Zaandam            9           2.0   
230            231           Tokelau            5           NaN   

     Total Recovered  Active Cases    Total Test    Population  
0        101322779.0     1741147.0  1.159833e+09  3.348053e+08  
1         44150289.0        1755.0  9.152658e+08  1.406632e+09  
2         39264546.0       95532.0  2.714902e+08  6.558452e+07  
3         37398100.0      216022.0  1.223324e+08  8.388360e+07  
4         35919372.0      208134.0  6.377617e+07  2.153536e+08  
..               ...           ...           ...           ...  
226            699.0           0.0           NaN           NaN  
227             29.0           0.0           NaN  7.990000e+02  
228              9.0           0.0           NaN  6.261610e+05  
229              7.0           0.0           NaN           NaN  
230              NaN           5.0           NaN  1.378000e+03  

[231 rows x 8 columns]

In [46]:
df.head()

Serial Number  Country  Total Cases  Total Deaths  Total Recovered  \
0              1      USA    104196861     1132935.0      101322779.0   
1              2    India     44682784      530740.0       44150289.0   
2              3   France     39524311      164233.0       39264546.0   
3              4  Germany     37779833      165711.0       37398100.0   
4              5   Brazil     36824580      697074.0       35919372.0   

   Active Cases    Total Test    Population  
0     1741147.0  1.159833e+09  3.348053e+08  
1        1755.0  9.152658e+08  1.406632e+09  
2       95532.0  2.714902e+08  6.558452e+07  
3      216022.0  1.223324e+08  8.388360e+07  
4      208134.0  6.377617e+07  2.153536e+08

In [47]:
df.tail()

Serial Number           Country  Total Cases  Total Deaths  \
226            227  Diamond Princess          712          13.0   
227            228      Vatican City           29           NaN   
228            229    Western Sahara           10           1.0   
229            230        MS Zaandam            9           2.0   
230            231           Tokelau            5           NaN   

     Total Recovered  Active Cases  Total Test  Population  
226            699.0           0.0         NaN         NaN  
227             29.0           0.0         NaN       799.0  
228              9.0           0.0         NaN    626161.0  
229              7.0           0.0         NaN         NaN  
230              NaN           5.0         NaN      1378.0

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Serial Number    231 non-null    int64  
 1   Country          231 non-null    object 
 2   Total Cases      231 non-null    int64  
 3   Total Deaths     225 non-null    float64
 4   Total Recovered  210 non-null    float64
 5   Active Cases     212 non-null    float64
 6   Total Test       213 non-null    float64
 7   Population       228 non-null    float64
dtypes: float64(5), int64(2), object(1)
memory usage: 14.6+ KB


In [49]:
df.describe()

Serial Number   Total Cases  Total Deaths  Total Recovered  \
count     231.000000  2.310000e+02  2.250000e+02     2.100000e+02   
mean      116.000000  2.923460e+06  3.005778e+04     2.993905e+06   
std        66.828138  9.479286e+06  1.053806e+05     9.520209e+06   
min         1.000000  5.000000e+00  1.000000e+00     2.000000e+00   
25%        58.500000  2.400100e+04  2.230000e+02     2.197250e+04   
50%       116.000000  2.065920e+05  2.179000e+03     2.351455e+05   
75%       173.500000  1.296146e+06  1.445200e+04     1.465768e+06   
max       231.000000  1.041969e+08  1.132935e+06     1.013228e+08   

       Active Cases    Total Test    Population  
count  2.120000e+02  2.130000e+02  2.280000e+02  
mean   9.099885e+04  3.249316e+07  2.849326e+07  
std    7.663888e+05  1.177370e+08  1.022803e+08  
min    0.000000e+00  7.850000e+03  7.990000e+02  
25%    5.250000e+01  3.478150e+05  4.450815e+05  
50%    1.115000e+03  2.216193e+06  5.676382e+06  
75%    1.022875e+04  1.298426e+07  2.170759e+07  
max    1.095262e+07  1.159833e+09  1.406632e+09

In [51]:
!pip install matplotlib


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
